In [4]:
import numpy as np
import pandas as pd

In [8]:
df = pd.read_csv('Life_Expectancy_100k.csv')

In [10]:
df

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,Eritrea,2005.022918,Developing,59.498152,35.941244,5.349239,1.193008,0.000000,96.457838,0.000000,...,96.039634,2.968242,96.011645,1.603202,220.534362,0.000000e+00,9.382659,9.482680,0.000000,5.350502
1,Italy,2002.993621,Developed,79.789966,71.882882,2.646028,9.293998,3502.952605,94.972374,11000.460332,...,96.971534,8.153363,96.474452,0.188650,27373.907239,5.760058e+06,0.471493,0.482139,0.841103,15.366307
2,Haiti,2007.029883,Developing,61.854804,264.347493,16.857589,6.009822,70.360616,NaN,12.444192,...,62.270975,5.592974,63.061902,2.735857,472.212397,9.196516e+06,4.268267,4.127897,0.458291,8.378936
3,Guinea-Bissau,2010.070270,Developing,56.641025,285.274033,3.665957,3.230872,61.615307,82.909580,86.878323,...,82.046876,6.703585,82.600963,5.889501,474.351091,3.303686e+05,8.033281,7.969854,0.403920,8.898468
4,Malta,2010.989197,Developed,86.968819,58.574112,0.905168,6.907417,3609.685568,82.360936,3.952482,...,96.202561,9.563071,96.127202,0.032924,22798.962211,0.000000e+00,0.764719,0.738030,0.826440,14.835954
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,Solomon Islands,2000.989608,Developing,66.079566,226.462667,0.000000,0.754044,327.310940,82.960159,0.000000,...,87.918107,6.458128,84.066489,0.177849,1218.400848,0.000000e+00,1.351381,1.440953,0.440977,6.627139
99996,Turkmenistan,2008.973711,Developing,65.653872,214.145534,3.268372,2.345552,22.296396,96.900812,216.078508,...,96.715860,1.838393,95.581046,0.134195,324.642892,7.385457e+04,3.176328,3.334908,0.000878,10.496627
99997,Venezuela (Bolivarian Republic of),2003.018879,Developing,72.415240,171.155264,10.980625,6.290124,0.000000,71.884788,112.174526,...,85.935897,4.989575,67.784715,0.078616,NaN,NaN,1.767000,1.640797,0.690494,11.607961
99998,Venezuela (Bolivarian Republic of),2010.990261,Developing,73.881493,156.667475,9.545446,6.707684,0.000000,78.155916,9.307906,...,77.939698,5.226577,77.999561,0.067799,NaN,NaN,1.586166,1.480504,0.754138,14.095774
99999,Lithuania,2006.005540,Developed,75.898576,228.555226,0.000000,12.633495,115.755241,95.151596,122.109737,...,94.540110,6.205879,93.465265,0.050831,1186.350372,1.306701e+06,3.078013,3.059063,0.807212,16.459848

In [12]:
pd.set_option('display.max_columns', None)
df

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,BMI,under-five deaths,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,Eritrea,2005.022918,Developing,59.498152,35.941244,5.349239,1.193008,0.000000,96.457838,0.000000,14.035581,13.193014,96.039634,2.968242,96.011645,1.603202,220.534362,0.000000e+00,9.382659,9.482680,0.000000,5.350502
1,Italy,2002.993621,Developed,79.789966,71.882882,2.646028,9.293998,3502.952605,94.972374,11000.460332,57.104179,3.269894,96.971534,8.153363,96.474452,0.188650,27373.907239,5.760058e+06,0.471493,0.482139,0.841103,15.366307
2,Haiti,2007.029883,Developing,61.854804,264.347493,16.857589,6.009822,70.360616,NaN,12.444192,4.800736,20.114558,62.270975,5.592974,63.061902,2.735857,472.212397,9.196516e+06,4.268267,4.127897,0.458291,8.378936
3,Guinea-Bissau,2010.070270,Developing,56.641025,285.274033,3.665957,3.230872,61.615307,82.909580,86.878323,23.062492,6.833136,82.046876,6.703585,82.600963,5.889501,474.351091,3.303686e+05,8.033281,7.969854,0.403920,8.898468
4,Malta,2010.989197,Developed,86.968819,58.574112,0.905168,6.907417,3609.685568,82.360936,3.952482,68.068079,1.002423,96.202561,9.563071,96.127202,0.032924,22798.962211,0.000000e+00,0.764719,0.738030,0.826440,14.835954
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,Solomon Islands,2000.989608,Developing,66.079566,226.462667,0.000000,0.754044,327.310940,82.960159,0.000000,38.733397,0.694737,87.918107,6.458128,84.066489,0.177849,1218.400848,0.000000e+00,1.351381,1.440953,0.440977,6.627139
99996,Turkmenistan,2008.973711,Developing,65.653872,214.145534,3.268372,2.345552,22.296396,96.900812,216.078508,43.667127,8.163289,96.715860,1.838393,95.581046,0.134195,324.642892,7.385457e+04,3.176328,3.334908,0.000878,10.496627
99997,Venezuela (Bolivarian Republic of),2003.018879,Developing,72.415240,171.155264,10.980625,6.290124,0.000000,71.884788,112.174526,55.314037,11.818729,85.935897,4.989575,67.784715,0.078616,NaN,NaN,1.767000,1.640797,0.690494,11.607961
99998,Venezuela (Bolivarian Republic of),2010.990261,Developing,73.881493,156.667475,9.545446,6.707684,0.000000,78.155916,9.307906,60.103290,12.357174,77.939698,5.226577,77.999561,0.067799,NaN,NaN,1.586166,1.480504,0.754138,14.095774
99999,Lithuania,2006.005540,Developed,75.898576,228.555226,0.000000,12.633495,115.755241,95.151596,122.109737,58.810586,0.764411,94.540110,6.205879,93.465265,0.050831,1186.350372,1.306701e+06,3.078013,3.059063,0.807212,16.459848

In [13]:
df.head()

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,BMI,under-five deaths,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,Eritrea,2005.022918,Developing,59.498152,35.941244,5.349239,1.193008,0.000000,96.457838,0.000000,14.035581,13.193014,96.039634,2.968242,96.011645,1.603202,220.534362,0.000000e+00,9.382659,9.482680,0.000000,5.350502
1,Italy,2002.993621,Developed,79.789966,71.882882,2.646028,9.293998,3502.952605,94.972374,11000.460332,57.104179,3.269894,96.971534,8.153363,96.474452,0.188650,27373.907239,5.760058e+06,0.471493,0.482139,0.841103,15.366307
2,Haiti,2007.029883,Developing,61.854804,264.347493,16.857589,6.009822,70.360616,NaN,12.444192,4.800736,20.114558,62.270975,5.592974,63.061902,2.735857,472.212397,9.196516e+06,4.268267,4.127897,0.458291,8.378936
3,Guinea-Bissau,2010.070270,Developing,56.641025,285.274033,3.665957,3.230872,61.615307,82.909580,86.878323,23.062492,6.833136,82.046876,6.703585,82.600963,5.889501,474.351091,3.303686e+05,8.033281,7.969854,0.403920,8.898468
4,Malta,2010.989197,Developed,86.968819,58.574112,0.905168,6.907417,3609.685568,82.360936,3.952482,68.068079,1.002423,96.202561,9.563071,96.127202,0.032924,22798.962211,0.000000e+00,0.764719,0.738030,0.826440,14.835954

In [14]:
df.tail()

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,BMI,under-five deaths,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
99995,Solomon Islands,2000.989608,Developing,66.079566,226.462667,0.000000,0.754044,327.310940,82.960159,0.000000,38.733397,0.694737,87.918107,6.458128,84.066489,0.177849,1218.400848,0.000000e+00,1.351381,1.440953,0.440977,6.627139
99996,Turkmenistan,2008.973711,Developing,65.653872,214.145534,3.268372,2.345552,22.296396,96.900812,216.078508,43.667127,8.163289,96.715860,1.838393,95.581046,0.134195,324.642892,7.385457e+04,3.176328,3.334908,0.000878,10.496627
99997,Venezuela (Bolivarian Republic of),2003.018879,Developing,72.415240,171.155264,10.980625,6.290124,0.000000,71.884788,112.174526,55.314037,11.818729,85.935897,4.989575,67.784715,0.078616,NaN,NaN,1.767000,1.640797,0.690494,11.607961
99998,Venezuela (Bolivarian Republic of),2010.990261,Developing,73.881493,156.667475,9.545446,6.707684,0.000000,78.155916,9.307906,60.103290,12.357174,77.939698,5.226577,77.999561,0.067799,NaN,NaN,1.586166,1.480504,0.754138,14.095774
99999,Lithuania,2006.005540,Developed,75.898576,228.555226,0.000000,12.633495,115.755241,95.151596,122.109737,58.810586,0.764411,94.540110,6.205879,93.465265,0.050831,1186.350372,1.306701e+06,3.078013,3.059063,0.807212,16.459848

In [16]:
df.columns

Index(['Country', 'Year', 'Status', 'Life expectancy ', 'Adult Mortality',
       'infant deaths', 'Alcohol', 'percentage expenditure', 'Hepatitis B',
       'Measles ', ' BMI ', 'under-five deaths ', 'Polio', 'Total expenditure',
       'Diphtheria ', ' HIV/AIDS', 'GDP', 'Population',
       ' thinness  1-19 years', ' thinness 5-9 years',
       'Income composition of resources', 'Schooling'],
      dtype='object')

In [17]:
# Old column names
old_cols = ['Country', 'Year', 'Status', 'Life expectancy ', 'Adult Mortality',
       'infant deaths', 'Alcohol', 'percentage expenditure', 'Hepatitis B',
       'Measles ', ' BMI ', 'under-five deaths ', 'Polio', 'Total expenditure',
       'Diphtheria ', ' HIV/AIDS', 'GDP', 'Population',
       ' thinness  1-19 years', ' thinness 5-9 years',
       'Income composition of resources', 'Schooling']

# New clean column names
new_cols = [
    'country', 'year', 'status', 'life_expectancy', 'adult_mortality',
    'infant_deaths', 'alcohol', 'percentage_expenditure', 'hepatitis_b',
    'measles', 'bmi', 'under_five_deaths', 'polio', 'total_expenditure',
    'diphtheria', 'hiv_aids', 'gdp', 'population',
    'thinness_10_19_years', 'thinness_5_9_years',
    'income_composition_of_resources', 'schooling'
]

# Rename using dictionary
df = df.rename(columns=dict(zip(old_cols, new_cols)))

# check result
print(df.columns)

Index(['country', 'year', 'status', 'life_expectancy', 'adult_mortality',
       'infant_deaths', 'alcohol', 'percentage_expenditure', 'hepatitis_b',
       'measles', 'bmi', 'under_five_deaths', 'polio', 'total_expenditure',
       'diphtheria', 'hiv_aids', 'gdp', 'population', 'thinness_10_19_years',
       'thinness_5_9_years', 'income_composition_of_resources', 'schooling'],
      dtype='object')

In [18]:
df.country.value_counts()

country
Georgia                  617
Belarus                  611
Bahamas                  602
Lebanon                  600
Solomon Islands          598
                        ...
Cook Islands              28
Saint Kitts and Nevis     27
San Marino                26
Marshall Islands          25
Nauru                     23
Name: count, Length: 193, dtype: int64

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 22 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   country                          100000 non-null  object
 1   year                             100000 non-null  float64
 2   status                           100000 non-null  object
 3   life_expectancy                  99673 non-null   float64
 4   adult_mortality                  99673 non-null   float64
 5   infant_deaths                    100000 non-null  float64
 6   alcohol                          93465 non-null   float64
 7   percentage_expenditure           100000 non-null  float64
 8   hepatitis_b                      81265 non-null   float64
 9   measles                          100000 non-null  float64
 10  bmi                              98793 non-null   float64
 11  under_five_deaths                100000 non-null  float64
 12  polio                            99306 non-null   float64
 13  total_expenditure                92339 non-null   float64
 14  diphtheria                       99306 non-null   float64
 15  hiv_aids                         100000 non-null  float64
 16  gdp                              84949 non-null   float64
 17  population                       78026 non-null   float64
 18  thinness_10_19_years             98793 non-null   float64
 19  thinness_5_9_years               98793 non-null   float64
 20  income_composition_of_resources  94388 non-null   float64
 21  schooling                        94497 non-null   float64
dtypes: float64(20), object(2)
memory usage: 16.8+ MB

In [20]:
x = df.drop('life_expectancy', axis=1)
y = df['life_expectancy']

In [21]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [22]:
x_train.head()

,country,year,status,adult_mortality,infant_deaths,alcohol,percentage_expenditure,hepatitis_b,measles,bmi,under_five_deaths,polio,total_expenditure,diphtheria,hiv_aids,gdp,population,thinness_10_19_years,thinness_5_9_years,income_composition_of_resources,schooling
75220,Kazakhstan,2010.034002,Developing,237.188791,6.302446,6.757593,0.000000,98.810817,4.444368,48.857204,9.357944,97.843605,4.448568,98.886609,0.034040,152.216860,1.588407e+07,2.366870,2.463978,0.761572,14.506495
48955,Norway,2000.982618,Developed,81.810654,0.000000,5.446212,6361.343003,NaN,121.799488,54.497681,0.624144,91.026471,8.661836,91.235628,0.118269,38526.286982,5.099934e+06,0.832506,0.701184,0.917841,17.480628
44966,Finland,2012.985747,Developing,79.161312,0.000000,8.980218,6116.599028,NaN,0.000000,61.426169,1.986924,98.034875,9.554115,98.442232,0.147039,49672.400066,5.955341e+06,0.941874,0.773659,0.885082,16.936467
13568,Tunisia,2005.972101,Developing,11.597841,2.688331,1.456876,415.432466,99.281926,0.000000,53.116337,5.032290,98.743097,5.596110,98.702694,0.100061,3486.787597,1.046870e+06,6.299699,6.273516,0.688328,14.230148
92727,Saint Lucia,2014.049510,Developing,137.319490,0.000000,9.945604,0.000000,99.358773,80.259869,46.890020,0.000000,99.093507,6.715383,98.916163,0.101441,NaN,NaN,4.262814,4.351511,0.723268,13.123338

In [23]:
data = x_train.copy()

In [24]:
data_numeric = data.select_dtypes(include=np.number)
data_numeric.head()

,year,adult_mortality,infant_deaths,alcohol,percentage_expenditure,hepatitis_b,measles,bmi,under_five_deaths,polio,total_expenditure,diphtheria,hiv_aids,gdp,population,thinness_10_19_years,thinness_5_9_years,income_composition_of_resources,schooling
75220,2010.034002,237.188791,6.302446,6.757593,0.000000,98.810817,4.444368,48.857204,9.357944,97.843605,4.448568,98.886609,0.034040,152.216860,1.588407e+07,2.366870,2.463978,0.761572,14.506495
48955,2000.982618,81.810654,0.000000,5.446212,6361.343003,NaN,121.799488,54.497681,0.624144,91.026471,8.661836,91.235628,0.118269,38526.286982,5.099934e+06,0.832506,0.701184,0.917841,17.480628
44966,2012.985747,79.161312,0.000000,8.980218,6116.599028,NaN,0.000000,61.426169,1.986924,98.034875,9.554115,98.442232,0.147039,49672.400066,5.955341e+06,0.941874,0.773659,0.885082,16.936467
13568,2005.972101,11.597841,2.688331,1.456876,415.432466,99.281926,0.000000,53.116337,5.032290,98.743097,5.596110,98.702694,0.100061,3486.787597,1.046870e+06,6.299699,6.273516,0.688328,14.230148
92727,2014.049510,137.319490,0.000000,9.945604,0.000000,99.358773,80.259869,46.890020,0.000000,99.093507,6.715383,98.916163,0.101441,NaN,NaN,4.262814,4.351511,0.723268,13.123338

In [25]:
data_categorical = data.select_dtypes(exclude=np.number)
data_categorical.head()

           country      status
75220   Kazakhstan  Developing
48955       Norway   Developed
44966      Finland  Developing
13568      Tunisia  Developing
92727  Saint Lucia  Developing

In [26]:
# EDA
df

,country,year,status,life_expectancy,adult_mortality,infant_deaths,alcohol,percentage_expenditure,hepatitis_b,measles,bmi,under_five_deaths,polio,total_expenditure,diphtheria,hiv_aids,gdp,population,thinness_10_19_years,thinness_5_9_years,income_composition_of_resources,schooling
0,Eritrea,2005.022918,Developing,59.498152,35.941244,5.349239,1.193008,0.000000,96.457838,0.000000,14.035581,13.193014,96.039634,2.968242,96.011645,1.603202,220.534362,0.000000e+00,9.382659,9.482680,0.000000,5.350502
1,Italy,2002.993621,Developed,79.789966,71.882882,2.646028,9.293998,3502.952605,94.972374,11000.460332,57.104179,3.269894,96.971534,8.153363,96.474452,0.188650,27373.907239,5.760058e+06,0.471493,0.482139,0.841103,15.366307
2,Haiti,2007.029883,Developing,61.854804,264.347493,16.857589,6.009822,70.360616,NaN,12.444192,4.800736,20.114558,62.270975,5.592974,63.061902,2.735857,472.212397,9.196516e+06,4.268267,4.127897,0.458291,8.378936
3,Guinea-Bissau,2010.070270,Developing,56.641025,285.274033,3.665957,3.230872,61.615307,82.909580,86.878323,23.062492,6.833136,82.046876,6.703585,82.600963,5.889501,474.351091,3.303686e+05,8.033281,7.969854,0.403920,8.898468
4,Malta,2010.989197,Developed,86.968819,58.574112,0.905168,6.907417,3609.685568,82.360936,3.952482,68.068079,1.002423,96.202561,9.563071,96.127202,0.032924,22798.962211,0.000000e+00,0.764719,0.738030,0.826440,14.835954
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,Solomon Islands,2000.989608,Developing,66.079566,226.462667,0.000000,0.754044,327.310940,82.960159,0.000000,38.733397,0.694737,87.918107,6.458128,84.066489,0.177849,1218.400848,0.000000e+00,1.351381,1.440953,0.440977,6.627139
99996,Turkmenistan,2008.973711,Developing,65.653872,214.145534,3.268372,2.345552,22.296396,96.900812,216.078508,43.667127,8.163289,96.715860,1.838393,95.581046,0.134195,324.642892,7.385457e+04,3.176328,3.334908,0.000878,10.496627
99997,Venezuela (Bolivarian Republic of),2003.018879,Developing,72.415240,171.155264,10.980625,6.290124,0.000000,71.884788,112.174526,55.314037,11.818729,85.935897,4.989575,67.784715,0.078616,NaN,NaN,1.767000,1.640797,0.690494,11.607961
99998,Venezuela (Bolivarian Republic of),2010.990261,Developing,73.881493,156.667475,9.545446,6.707684,0.000000,78.155916,9.307906,60.103290,12.357174,77.939698,5.226577,77.999561,0.067799,NaN,NaN,1.586166,1.480504,0.754138,14.095774
99999,Lithuania,2006.005540,Developed,75.898576,228.555226,0.000000,12.633495,115.755241,95.151596,122.109737,58.810586,0.764411,94.540110,6.205879,93.465265,0.050831,1186.350372,1.306701e+06,3.078013,3.059063,0.807212,16.459848